"""Small, English-grounded cybersecurity concept references.

The English definitions are curated engineering guidance. The Yoruba/Igbo wording
is NOT certified; preserve familiar technical acronyms pending fluent review.
This is prompt grounding, not an authority to override user instructions.
"""
import re

REFERENCES = {
    "mfa": (
        "MFA (Multi-Factor Authentication) requires at least TWO DIFFERENT "
        "authentication factor CATEGORIES, not necessarily three. Categories: "
        "knowledge (password or PIN), possession (registered authenticator "
        "app/device or security key), inherence (fingerprint or face). "
        "Correct example: password plus a code generated by an authenticator app. "
        "Incorrect: password plus security question (both knowledge). "
        "A telephone number alone does not prove device possession. "
        "A username is an identifier, not an authentication factor. "
        "MFA reduces risk but does not guarantee protection."
    ),
    "otp": (
        "OTP means One-Time Password: a short-lived verification code used "
        "to confirm sign-in or a transaction. Never disclose it to any caller "
        "including someone claiming to work for a bank. Independently verify "
        "unexpected requests using the official bank app or a trusted number. "
        "Do not translate OTP as a type of money or tax."
    ),
    "phishing": (
        "Phishing is deception through messages or websites intended to steal "
        "credentials or manipulate people. Warning signs include unexpected "
        "requests for OTP/PIN/password, urgent threats and suspicious links. "
        "Sender display names, apparent phone numbers and websites can be "
        "spoofed; spelling alone is not proof. Independently verify via the "
        "official app or a trusted number; avoid embedded links."
    ),
}
TERM_GUIDANCE = (
    "When responding in Igbo or Yoruba, keep exact labels 'MFA' and 'OTP' "
    "and optionally the original English expansions once; explain the meaning "
    "in the requested language without making up a literal translation. "
    "Use short sentences, one concrete example, and finish the final sentence. "
    "Do not number or list all three MFA categories unless the user asks: "
    "explain that any TWO distinct categories suffice. "
    "These reference facts take priority over an inaccurate example in the question."
)

def detect_topic(question):
    """Choose only a clearly mentioned topic; otherwise use generic tutor guidance."""
    question = question.lower()
    if re.search(r"\bmfa\b|multi[- ]factor authentication", question):
        return "mfa"
    if re.search(r"\botp\b|one[- ]time password", question):
        return "otp"
    if re.search(r"\bphishing\b|account[- ]verification message", question):
        return "phishing"
    return None

def reference_for_question(question):
    topic = detect_topic(question)
    if topic is None:
        return ""
    return "Ground the answer in these verified English concept facts: " + REFERENCES[topic] + " " + TERM_GUIDANCE

def response_warnings(text, topic, completion_tokens=None):
    """Screening flags, not a factual-quality or translation certification."""
    if not isinstance(text, str) or not text.strip():
        return ["empty_response"]
    stripped = text.strip()
    warnings = []
    if completion_tokens == 320:
        warnings.append("possible_token_limit")
    if stripped[-1] not in ".!?。！？":
        warnings.append("possibly_incomplete_ending")
    low = stripped.lower()
    if topic == "mfa":
        # Specific English error strings from observed benchmark regressions.
        if re.search(r"three[- ]factor authentication|three factors (?:are|is) (?:always )?required", low):
            warnings.append("three_factor_claim")
        if "password plus a security question is mfa" in low:
            warnings.append("two_knowledge_factors")
        if "phone number is a possession factor" in low:
            warnings.append("phone_number_not_possession")
        # Observed Yoruba wording: a translation-review flag, not a verified error detector.
        if "ìdánimọ̀ mẹta" in low or "ọ̀nà mẹta" in low:
            warnings.append("yoruba_three_factor_wording_review")
        if "naanị aha njirimara gị" in low:
            warnings.append("igbo_username_claim_review")
    if topic == "otp":
        if "ote time password" in low or "owo-igba kan" in low:
            warnings.append("otp_terminology_review")
    return warnings
